//! Conformance tests for the Excel tools against real `.xlsx` fixtures
//! generated by `openpyxl` (the same library `kitty_docs_web.py` used) as an
//! independent oracle — mirrors `word_conformance.rs`'s philosophy.

use std::path::PathBuf;
use std::process::Command;

use kitty_tools::tools::excel::{excel_inspect, excel_read_rows};
use serde_json::Value;

fn run_python(script: &str) -> String {
    let output = Command::new("python")
        .arg("-c")
        .arg(script)
        .output()
        .expect("failed to run python");
    if !output.status.success() {
        panic!(
            "python script failed:\nstdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    String::from_utf8_lossy(&output.stdout).trim().to_string()
}

fn tmp_path(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "kitty-tools-excel-test-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    dir.join(name)
}

fn parse(json_str: &str) -> Value {
    serde_json::from_str(json_str).expect("tool output was not valid JSON")
}

#[test]
fn inspect_lists_sheets_headers_and_dimensions() {
    let path = tmp_path("inspect.xlsx");
    run_python(&format!(
        r#"
from openpyxl import Workbook
wb = Workbook()
ws = wb.active
ws.title = "Data"
ws.append(["id", "name"])
ws.append([1, "alpha"])
ws.append([2, "beta"])
ws.append([3, "gamma"])
wb.save(r"{}")
print("OK")
"#,
        path.display()
    ));

    let v = parse(&excel_inspect(&path.to_string_lossy()));
    assert_eq!(v["status"], "success", "{v}");
    assert_eq!(v["data"]["sheet_names"], serde_json::json!(["Data"]));
    assert_eq!(v["data"]["active_sheet"], "Data");
    assert_eq!(v["data"]["headers"], serde_json::json!(["id", "name"]));
    assert_eq!(v["data"]["max_rows"], 4);
    assert_eq!(v["data"]["max_cols"], 2);
    assert!(v["data"]["dimensions"].as_str().unwrap().contains('4'), "{v}");
}

#[test]
fn read_rows_caps_and_paginates() {
    let path = tmp_path("big.xlsx");    run_python(&format!(
        r#"
from openpyxl import Workbook
wb = Workbook()
ws = wb.active
ws.append(["id", "name"])
for i in range(600):
    ws.append([i, f"row{{i}}"])
wb.save(r"{}")
print("OK")
"#,
        path.display()
    ));

    let first = parse(&excel_read_rows(&path.to_string_lossy(), None, None, "json", None, 0));
    assert_eq!(first["status"], "success", "{first}");
    assert_eq!(first["truncated"], true);
    assert_eq!(first["data"].as_array().unwrap().len(), 500);
    assert_eq!(first["metadata"]["total_rows"], 600);
    assert_eq!(first["metadata"]["next_offset"], 500);
    // 600 id rows follow the header row; page 1 covers ids 0..=499.
    assert_eq!(first["data"][499]["id"], 499);

    let second = parse(&excel_read_rows(
        &path.to_string_lossy(),
        None,
        None,
        "json",
        None,
        first["metadata"]["next_offset"].as_u64().unwrap() as usize,
    ));
    assert_eq!(second["truncated"], false);
    assert_eq!(second["data"][0]["id"], 500);
}

#[test]
fn read_rows_honors_sheet_and_range_box() {
    let path = tmp_path("multi.xlsx");
    run_python(&format!(
        r#"
from openpyxl import Workbook
wb = Workbook()
ws1 = wb.active
ws1.title = "First"
ws1.append(["a", "b"])
ws1.append([1, 2])
ws1.append([3, 4])
ws2 = wb.create_sheet("Second")
ws2.append(["x", "y"])
ws2.append([9, 8])
wb.save(r"{}")
print("OK")
"#,
        path.display()
    ));

    // Default picks the first sheet.
    let v = parse(&excel_read_rows(&path.to_string_lossy(), None, None, "json", None, 0));
    assert_eq!(v["data"][0]["a"], 1);

    // Explicit sheet selection.
    let v2 = parse(&excel_read_rows(&path.to_string_lossy(), Some("Second"), None, "json", None, 0));
    assert_eq!(v2["data"][0]["x"], 9);

    // Range box on the first sheet: "A1:B2" -> headers row 1, data row 2.
    let v3 = parse(&excel_read_rows(&path.to_string_lossy(), Some("First"), Some("A1:B2"), "json", None, 0));
    assert_eq!(v3["data"][0]["a"], 1);
    assert_eq!(v3["data"][0]["b"], 2);
}

#[test]
fn read_rows_csv_output() {
    let path = tmp_path("csv.xlsx");
    run_python(&format!(
        r#"
from openpyxl import Workbook
wb = Workbook()
ws = wb.active
ws.append(["id", "name"])
ws.append([1, "alpha"])
ws.append([2, "beta"])
wb.save(r"{}")
print("OK")
"#,
        path.display()
    ));

    let v = parse(&excel_read_rows(&path.to_string_lossy(), None, None, "csv", None, 0));
    assert_eq!(v["status"], "success", "{v}");
    let csv = v["data"].as_str().unwrap();
    assert!(csv.contains("id,name"), "got: {csv}");
    assert!(csv.contains("1,alpha"), "got: {csv}");
    assert!(csv.contains("2,beta"), "got: {csv}");
}

#[test]
fn read_rows_errors() {
    let dir = std::env::temp_dir().join(format!("kitty-tools-excel-missing-{}", std::process::id()));
    let not_found = excel_read_rows(
        dir.join("does-not-exist.xlsx").to_str().unwrap(),
        None,
        None,
        "json",
        None,
        0,
    );
    let v = parse(&not_found);
    assert_eq!(v["error_code"], "XLSX_NOT_FOUND");

    let path = tmp_path("one_sheet.xlsx");
    run_python(&format!(
        r#"
from openpyxl import Workbook
wb = Workbook()
ws = wb.active
ws.append(["id"])
ws.append([1])
wb.save(r"{}")
print("OK")
"#,
        path.display()
    ));
    let bad_sheet = excel_read_rows(&path.to_string_lossy(), Some("Nope"), None, "json", None, 0);
    let v2 = parse(&bad_sheet);
    assert_eq!(v2["error_code"], "XLSX_BAD_SHEET");
}

