//! Conformance tests calling the tool functions in-process (no MCP
//! transport) against real .docx fixtures — mirrors the base plan's
//! `tests/conformance.rs` philosophy. Fixtures are generated by shelling
//! out to `python-docx` (the same library `lean_mcp.py` used), and
//! `word_write_doc`'s output is verified by reading it back with
//! `python-docx` as an independent oracle, not just this crate's own
//! reader.

use std::path::{Path, PathBuf};
use std::process::Command;

use kitty_tools::server::{
    KittyToolsServer, WordReadOutlineRequest, WordReadTextRequest, WordWriteDocRequest,
    WordWriteModeParam,
};
use rmcp::handler::server::wrapper::Parameters;
use serde_json::Value;

fn python() -> &'static str {
    "python"
}

fn run_python(script: &str) -> String {
    let output = Command::new(python())
        .arg("-c")
        .arg(script)
        .output()
        .expect("failed to run python");
    if !output.status.success() {
        panic!(
            "python script failed:\nstdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    String::from_utf8_lossy(&output.stdout).trim().to_string()
}

fn tmp_path(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "kitty-tools-test-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    dir.join(name)
}

fn parse(json_str: &str) -> Value {
    serde_json::from_str(json_str).expect("tool output was not valid JSON")
}

#[test]
fn word_read_text_reaches_table_only_content() {
    let path = tmp_path("table_only.docx");
    // A document whose body has one stray title paragraph and all other
    // content inside a table — the exact shape that made the old
    // "standard, else robust" gate return just one paragraph.
    run_python(&format!(
        r#"
from docx import Document
doc = Document()
doc.add_paragraph("Title Paragraph")
table = doc.add_table(rows=3, cols=2)
table.cell(0, 0).text = "Row1Col1"
table.cell(0, 1).text = "Row1Col2"
table.cell(1, 0).text = "Row2Col1"
table.cell(1, 1).text = "Row2Col2"
table.cell(2, 0).text = "Row3Col1"
table.cell(2, 1).text = "Row3Col2"
doc.save(r"{}")
"#,
        path.display()
    ));

    let server = KittyToolsServer::new();
    let result = server.word_read_text(Parameters(WordReadTextRequest {
        path: path.to_string_lossy().to_string(),
        query: None,
        offset: None,
        limit: None,
    }));
    let v = parse(&result);
    assert_eq!(v["status"], "success");
    let data = v["data"].as_array().unwrap();
    let joined: String = data.iter().map(|x| x.as_str().unwrap()).collect::<Vec<_>>().join(" ");
    assert!(joined.contains("Title Paragraph"));
    assert!(joined.contains("Row1Col1"));
    assert!(joined.contains("Row3Col2"));
    assert!(data.len() >= 7, "expected title + 6 cells, got {data:?}");
}

#[test]
fn word_read_text_paginates() {
    let path = tmp_path("many_paragraphs.docx");
    run_python(&format!(
        r#"
from docx import Document
doc = Document()
for i in range(250):
    doc.add_paragraph(f"Paragraph number {{i}}")
doc.save(r"{}")
"#,
        path.display()
    ));

    let server = KittyToolsServer::new();
    let first = parse(&server.word_read_text(Parameters(WordReadTextRequest {
        path: path.to_string_lossy().to_string(),
        query: None,
        offset: None,
        limit: None,
    })));
    assert_eq!(first["truncated"], true);
    assert_eq!(first["metadata"]["total_paragraphs"], 250);
    let next_offset = first["metadata"]["next_offset"].as_u64().unwrap();
    assert_eq!(next_offset, 200);

    let second = parse(&server.word_read_text(Parameters(WordReadTextRequest {
        path: path.to_string_lossy().to_string(),
        query: None,
        offset: Some(next_offset as u32),
        limit: None,
    })));
    assert_eq!(second["truncated"], false);
    let data = second["data"].as_array().unwrap();
    assert_eq!(data.len(), 50);
    assert_eq!(data[0], "Paragraph number 200");
}

#[test]
fn word_read_outline_resolves_style_id_to_name() {
    let path = tmp_path("headings.docx");
    run_python(&format!(
        r#"
from docx import Document
doc = Document()
doc.add_heading("Top Level", level=1)
doc.add_paragraph("Body text under top level.")
doc.add_heading("Sub Level", level=2)
doc.save(r"{}")
"#,
        path.display()
    ));

    let server = KittyToolsServer::new();
    let result = parse(&server.word_read_outline(Parameters(WordReadOutlineRequest {
        path: path.to_string_lossy().to_string(),
    })));
    assert_eq!(result["status"], "success");
    let outline = result["data"].as_array().unwrap();
    assert_eq!(outline.len(), 2);
    assert_eq!(outline[0]["level"], 1);
    assert_eq!(outline[0]["text"], "Top Level");
    assert_eq!(outline[1]["level"], 2);
    assert_eq!(outline[1]["text"], "Sub Level");
}

#[test]
fn word_read_text_not_found_error() {
    let server = KittyToolsServer::new();
    // Inside home (temp dir) so the home boundary passes through to the
    // not-found error path.
    let result = parse(&server.word_read_text(Parameters(WordReadTextRequest {
        path: tmp_path("does-not-exist.docx").to_string_lossy().to_string(),
        query: None,
        offset: None,
        limit: None,
    })));
    assert_eq!(result["status"], "error");
    assert_eq!(result["error_code"], "DOCX_NOT_FOUND");
}

#[test]
fn word_write_doc_create_mode_opens_in_python_docx() {
    let path = tmp_path("created.docx");
    let server = KittyToolsServer::new();
    // Note: only the "|---|---|" line is a separator row per the ported
    // parser (matching `lean_mcp.py`'s exact behavior) — "| a | b |" is a
    // literal *data* row, not a header the parser special-cases.
    let doc_text = "# Heading One\n\nSome **bold** and *italic* text.\n\n- bullet one\n- bullet two\n\n1. first\n2. second\n\n| a | b |\n|---|---|\n| 1 | 2 |\n| 3 |";

    let result = parse(&server.word_write_doc(Parameters(WordWriteDocRequest {
        path: path.to_string_lossy().to_string(),
        doc_text: Some(doc_text.to_string()),
        write_mode: Some(WordWriteModeParam::Create),
        title: Some("My Test Doc".to_string()),
        language: Some("en-US".to_string()),
    })));
    assert_eq!(result["status"], "success", "{result:?}");
    assert!(path.exists());

    // Independent oracle: open with python-docx and verify structure.
    let check = run_python(&format!(
        r#"
from docx import Document
doc = Document(r"{}")
paras = [p.text for p in doc.paragraphs if p.text.strip()]
assert "My Test Doc" in paras[0], paras
assert any("Heading One" in p for p in paras), paras
assert any("bold" in p and "italic" in p for p in paras), paras
tables = doc.tables
assert len(tables) == 1, tables
t = tables[0]
# Row 0 is "| a | b |" (a literal data row — only "|---|---|" is skipped as
# a separator), row 1 is "1"/"2", row 2 is "3" with an empty trailing cell.
assert t.cell(0, 0).text == "a", t.cell(0, 0).text
assert t.cell(0, 1).text == "b", t.cell(0, 1).text
assert t.cell(1, 0).text == "1", t.cell(1, 0).text
assert t.cell(1, 1).text == "2", t.cell(1, 1).text
assert t.cell(2, 0).text == "3", t.cell(2, 0).text
assert t.cell(2, 1).text == "", repr(t.cell(2, 1).text)
print("OK")
"#,
        path.display()
    ));
    assert_eq!(check, "OK");
}

#[test]
fn word_write_doc_bold_and_italic_runs_are_actually_formatted() {
    let path = tmp_path("formatting.docx");
    let server = KittyToolsServer::new();
    server.word_write_doc(Parameters(WordWriteDocRequest {
        path: path.to_string_lossy().to_string(),
        doc_text: Some("**bold word** and *italic word*".to_string()),
        write_mode: Some(WordWriteModeParam::Create),
        title: None,
        language: None,
    }));

    let check = run_python(&format!(
        r#"
from docx import Document
doc = Document(r"{}")
body_paras = [p for p in doc.paragraphs if "bold word" in p.text]
assert body_paras, [p.text for p in doc.paragraphs]
p = body_paras[0]
bold_runs = [r for r in p.runs if r.bold and "bold word" in r.text]
italic_runs = [r for r in p.runs if r.italic and "italic word" in r.text]
assert bold_runs, [(r.text, r.bold, r.italic) for r in p.runs]
assert italic_runs, [(r.text, r.bold, r.italic) for r in p.runs]
print("OK")
"#,
        path.display()
    ));
    assert_eq!(check, "OK");
}

#[test]
fn word_write_doc_append_mode_preserves_existing_content_and_byte_identical_other_parts() {
    let path = tmp_path("append_target.docx");
    run_python(&format!(
        r#"
from docx import Document
doc = Document()
doc.add_paragraph("Original paragraph.")
doc.save(r"{}")
"#,
        path.display()
    ));

    // Snapshot every non-document.xml, non-styles.xml, non-core.xml part
    // before the append, to confirm the "byte-copy every part it doesn't
    // touch" fidelity claim.
    let before_hashes = zip_part_hashes(&path);

    let server = KittyToolsServer::new();
    let result = parse(&server.word_write_doc(Parameters(WordWriteDocRequest {
        path: path.to_string_lossy().to_string(),
        doc_text: Some("Appended paragraph.".to_string()),
        write_mode: Some(WordWriteModeParam::Append),
        title: None,
        language: Some("en-US".to_string()),
    })));
    assert_eq!(result["status"], "success", "{result:?}");

    let after_hashes = zip_part_hashes(&path);
    for (name, before) in &before_hashes {
        // document.xml is expected to change — that's the whole point of
        // append. styles.xml changes because of the `w:lang` metadata step.
        // Every other part (rels, content types, numbering, docProps/app)
        // must be byte-identical — this is the fidelity claim the
        // hand-rolled zip-splice approach is meant to deliver.
        if name == "word/document.xml" || name == "word/styles.xml" {
            continue;
        }
        let after = after_hashes
            .get(name)
            .unwrap_or_else(|| panic!("part {name} disappeared after append"));
        assert_eq!(after, before, "part {name} changed on append but shouldn't have");
    }

    let check = run_python(&format!(
        r#"
from docx import Document
doc = Document(r"{}")
texts = [p.text for p in doc.paragraphs if p.text.strip()]
assert "Original paragraph." in texts, texts
assert "Appended paragraph." in texts, texts
assert texts.index("Original paragraph.") < texts.index("Appended paragraph.")
print("OK")
"#,
        path.display()
    ));
    assert_eq!(check, "OK");
}

#[test]
fn word_read_outline_degrades_gracefully_on_a_dangling_style_id() {
    // Simulates the classic Google-Docs-export gap: a paragraph's `w:pStyle`
    // references a styleId absent from `word/styles.xml`. python-docx
    // raises `KeyError` on `.style.name` for this; the old lean_mcp.py
    // caught that but then reset `standard_elements = []`, discarding every
    // paragraph already collected and flipping the *whole document* to the
    // fallback path over one bad paragraph. Here there is no such gate to
    // mis-fire — degrade to treating it as a plain (non-heading) paragraph.
    let path = tmp_path("dangling_style.docx");
    run_python(&format!(
        r#"
import zipfile, shutil
from docx import Document
doc = Document()
doc.add_paragraph("Normal para")
doc.add_heading("A Heading", level=1)
doc.save(r"{path}")

with zipfile.ZipFile(r"{path}") as z:
    doc_xml = z.read("word/document.xml").decode("utf-8")
assert "Heading1" in doc_xml
patched = doc_xml.replace("Heading1", "DanglingGhostStyle", 1)

tmp2 = r"{path}" + ".tmp"
with zipfile.ZipFile(r"{path}") as zin, zipfile.ZipFile(tmp2, "w", zipfile.ZIP_DEFLATED) as zout:
    for item in zin.namelist():
        data = zin.read(item)
        if item == "word/document.xml":
            data = patched.encode("utf-8")
        zout.writestr(item, data)
shutil.move(tmp2, r"{path}")
"#,
        path = path.display()
    ));

    let server = KittyToolsServer::new();
    let outline_result = parse(&server.word_read_outline(Parameters(WordReadOutlineRequest {
        path: path.to_string_lossy().to_string(),
    })));
    assert_eq!(outline_result["status"], "success");
    // The dangling-style paragraph is no longer detected as a heading (its
    // styleId doesn't resolve to anything containing "heading"), so the
    // outline is empty — but critically, this must not error or panic, and
    // the *other* paragraph's presence is confirmed via word_read_text.
    assert_eq!(outline_result["data"].as_array().unwrap().len(), 0);

    let text_result = parse(&server.word_read_text(Parameters(WordReadTextRequest {
        path: path.to_string_lossy().to_string(),
        query: None,
        offset: None,
        limit: None,
    })));
    assert_eq!(text_result["status"], "success");
    let data = text_result["data"].as_array().unwrap();
    assert!(data.iter().any(|v| v.as_str() == Some("Normal para")));
    assert!(data.iter().any(|v| v.as_str() == Some("A Heading")));
}

#[test]
fn word_write_doc_append_to_missing_file_errors() {
    let server = KittyToolsServer::new();
    let result = parse(&server.word_write_doc(Parameters(WordWriteDocRequest {
        path: tmp_path("does-not-exist.docx").to_string_lossy().to_string(),
        doc_text: Some("text".to_string()),
        write_mode: Some(WordWriteModeParam::Append),
        title: None,
        language: None,
    })));
    assert_eq!(result["status"], "error");
    assert_eq!(result["error_code"], "DOCX_NOT_FOUND");
}

fn zip_part_hashes(path: &Path) -> std::collections::HashMap<String, u64> {
    use std::hash::{Hash, Hasher};
    let file = std::fs::File::open(path).unwrap();
    let mut archive = zip::ZipArchive::new(file).unwrap();
    let mut map = std::collections::HashMap::new();
    for i in 0..archive.len() {
        let mut entry = archive.by_index(i).unwrap();
        let name = entry.name().to_string();
        let mut buf = Vec::new();
        std::io::Read::read_to_end(&mut entry, &mut buf).unwrap();
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        buf.hash(&mut hasher);
        map.insert(name, hasher.finish());
    }
    map
}
